//Print a Statement using \n,\t,\b
#include<stdio.h>
#include<conio.h>
void main()
{	clrscr();
	printf("C");
	printf("\n\tis");
	printf("\n\t\ta");
	printf("\n\t\t\tmiddle");
	printf("\n\t\t\t\tlevel");
	printf("\n\t\t\t\t\tlanguage");
	printf("\n\t\t\t\t\tlanguage");
	printf("\n\t\t\t\tlevel");
	printf("\n\t\t\tmiddle");
	printf("\n\t\ta");
	printf("\n\tis");
	printf("\nC");
	getch();
}